# Generated by Django 4.2 on 2023-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop',
            field=models.CharField(default='cotton', max_length=255),
            preserve_default=False,
        ),
    ]
